version: '3'

services:
  nginx:
    build: .
    volumes: 
     - ./www/html/:/var/www/html/
    ports:
     - 80:8080
    restart: unless-stopped


  php:
    build: ./php/
    volumes:
     - ./www/html/:/var/www/html
    restart: unless-stopped
    ports:
     - 9090:9090
    depends_on: 
     - mysql  
        
  mysql:
    image: mysql
    volumes:
     - ./mysql:/var/lib/mysql
    environment:
     - MYSQL_ROOT_PASSWORD=rootpassword**456
     - MYSQL_DATABASE=mydb
     - MYSQL_USER=admin
     - MYSQL_PASSWORD=mysql_password345
    ports:
     - 3306:3307     
